// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hekktvidgupdncqwktdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhla2t0dmlkZ3VwZG5jcXdrdGRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4OTIyMzMsImV4cCI6MjA2MTQ2ODIzM30.4d6RSqW136LeAwhUTt4EM2O5y6VXBcIcNgRtHJF_ZKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);